name: QA/UAT Website Content Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # Ejecutar todos los días a las 7 UTC

permissions:
  contents: write

jobs:
  extract-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (por si queremos guardar resultados en repo)
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 markdownify

      - name: Extract and Analyze Pages
        run: |
          python scripts/analyze_website.py

      - name: Upload markdown output
        uses: actions/upload-artifact@v4
        with:
          name: qa-uat-generated-docs
          path: extracted_docs/
