name: Atlantyde Drawio Agent CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t atlantyde/drawio-agent .

    - name: Test export script
      run: |
        mkdir -p diagrams
        cp templates/base.drawio diagrams/test.drawio
        docker run --rm -v ${{ github.workspace }}/diagrams:/home/drawio/diagrams -it atlantyde/drawio-agent export_all.sh

    - name: Fix permissions
      run: |
        chmod -c -R +rX "_site/" | while read line; do echo "::warning title=Invalid file permissions automatically fixed::$line" done
    - name: Archive exported files
      uses: actions/upload-pages-artifact@v3
      name: exported-diagrams
      path: diagrams/*.pdf
